### ISSUE TITLE
Graph label disappears 1958-1970

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#108]
When hovering over the graph of data from 1958 - ~1970, the label disappears as you move it. Makes it hard to see a particular data point. 
Only on the pink/underside of the graph though. Video here: http://www.youtube.com/watch?v=jkzEw8St9no
Chrome browser on Windows

**Comment by grady-lad** [comment]
Will try reproduce this one!

**Comment by grady-lad** [comment]
The source of the problem here is that when you hover over the graph the information div appears where your mouse is hovering. This means that you are not hovering over the graph anymore hence the flickering.

One possible solution (and easiest) is to move the information divs so that they do not overlap with the hover functionality, like in the image below
<img width="1370" alt="screen shot 2017-11-29 at 19 59 07" src="https://user-images.githubusercontent.com/6424060/33409296-4df83dfa-d540-11e7-98fe-8a58229384a0.png">

If this solution is acceptable ill make the pr ? @titojankowski

**Comment by titojankowski** [comment]
Oh wow cool you figured out what was causing it, that makes sense! To
compare to the gold standard, I tested out what Coinbase does. They
simply disable the information div when the mouse is in the region of
the information div, across the entire chart. Is that an easy option
instead? I think the current positioning looks awesome so don't want to
move them as shown in your mockup.https://www.coinbase.com/charts


On Wed, Nov 29, 2017, at 06:03 PM, grady-lad wrote:
> The source of the problem here is that when you hover over the graph
> the information div appears where your mouse is hovering. This means
> that you are not hovering over the graph anymore hence the flickering.> One possible solution (and easiest) is to move the information divs so
> that they do not overlap with the hover functionality, like in the
> image below screen shot 2017-11-29 at 19 59 07> If this solution is acceptable ill make the pr ? @titojankowski[1]


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/titojankowski
  2. https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/issues/108#issuecomment-348059211

**Comment by grady-lad** [comment]
@titojankowski Current version is deployed with this fix ? Could you take a look when you get the chance ?

**Comment by titojankowski** [comment]
@grady-lad Nice fix! This is really coming together!!

**Comment by grady-lad** [comment]
done in #112
