### ISSUE TITLE
Purin/Tito treasure box: Take 1 week / 1 month out

### ISSUE THREAD

**Issue by decentral1se** [giving-a-fuck-about-climate-change/carbon-inferno#132]
Again, nothing else there, @titojankowski, any pointers? It's just not useful or?

**Comment by titojankowski** [comment]
I'm back to liking 1 WEEK and 1 MONTH. They add this sense of "now" to the whole thing. That sense of now is what's missing from the climate discussion, and what we're adding in by giving a fuck. I would really love it if we had intra-day data, and could see 1 DAY of data.

**Comment by grady-lad** [comment]
Well it looks like 1 week cannot generate a weeks worth of data if you are on the otherside of the world.

Because I am in Australia (pretty much a day ahead)  I can only get two data points out of a potential 7.

query: `?ordering=+date&date__range=2017-12-27,2018-01-03`

Result: 
<img width="1390" alt="screen shot 2018-01-03 at 00 26 00" src="https://user-images.githubusercontent.com/6424060/34485100-e0a54c3c-f01c-11e7-94e9-a413d4988bb3.png">

**Comment by titojankowski** [comment]
@grady-lad nice find! I don't quite get why that happens, maybe you could explain? There are 8 points in that dataset: http://api.carbondoomsday.com/api/co2/?date__range=2017-12-27%2C2018-01-03
