### ISSUE TITLE
Projected scenarios HN #16333355 comment

### ISSUE THREAD

**Issue by decentral1se** [giving-a-fuck-about-climate-change/carbon-inferno#166]
From https://news.ycombinator.com/item?id=16333355:

> Id also like to add that the majority of your first time visitors are gonna have no reference point for what a good or bad PPM is. It would be helpful to have projection scenarios for the future and introduce labels for specific points in the time line with significant theoretical effects at that carbon level.

There's more in the thread.

**Comment by lwm** [comment]
Purin just sent a possible design for a kind of 'projection' button. It's awesome!

<img width="1032" alt="purin-lines" src="https://user-images.githubusercontent.com/1991377/36249647-a3bd6f52-123b-11e8-8ddd-b1ebca5af905.png">

**Comment by grady-lad** [comment]
@lwm How can we continue on this? What is the  agreed "tipping point" ?, I think we'd need to clarify a that and how long into the future (up to what date) we would want the graph to display, before any work can be done on this.

**Comment by lwm** [comment]
Yeah, I'm not sure. We'd need to wrangle out something sensible. I kinda got the idea that Purin didn't have the details and was just saying - 'once you figure it out, it would cool this way'. I could be wrong.

I saw https://climate-life-events.herokuapp.com/ did something with future looking measurements.

@gschivley, do you have any ideas how we might achieve this? Any data sources?

**Comment by gschivley** [comment]
I downloaded a set of [CO₂ concentration scenarios](https://cmu.box.com/s/eugbdxsv6h63f9qjn4pw32ekeinnyigr) you can use. They are from the same model runs that I use in my life-events figure. A tiny bit of background - they are from the newest set of global climate scenarios (shared socioeconomic pathways [SSPs]) and are the outputs of a reduced form climate model (MAGICC) rather than general circulation models (GCMs). If you want more detailed model runs on older scenarios I'll have to search for those results.

In the file you'll see a model - scenario column. The last part of the string (e.g. 26, 34, 60, etc) represent radiative forcing (2.6 watts/m2) and seem to align with scenarios in the 2014 IPCC report. There are multiple results for each RF scenario that can be used to create a range of uncertainty. Because results are from a reduced form model they don't represent the full range of uncertainty - each set of results will eventually have its own uncertainty.

One point that I think is important. The 26 scenarios are around 2 deg C warming. To hit them will require *net* zero GHG emissions around mid-century (maybe by 2070). That might mean significant *negative* CO₂ emissions to offset land use, aviation, industrial sources, etc. Along those lines, [here's the CO₂ emissions](https://cmu.box.com/s/8ua7nkw03dctkuour605zhsjh4blorc4) associated with the concentration scenarios.

Hope that helps!
