### ISSUE TITLE
Some comments for improvement HN #16332964 comment

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#167]
From https://news.ycombinator.com/item?id=16332964:

> Some comments:
> 
> 1) The tagline at the top "since 1958" makes it seem like the website is since 1958, instead of the data. Obviously false, but may reduce trust.
> 
> 2) The graph is good, I like it!
> 
> 3) In the Data Sources section, it would be very helpful to have a link to the original data. Don't make me hunt for it. I was wondering if this was an average of multiple locations or from a single location.
> 
> 4) It may be helpful to have a link or explanation about the yearly period of the CO2 level. Something like https://www.co2.earth/seasonal-co2-cycle.

**Comment by YPCrumble** [comment]
I don't see why the "since 1958" would reduce trust. The data has been collected since 1958. 

I'm pushing a quick PR for number three. 

I also suggest an "FAQs" section in the wiki that could answer a bunch of the questions in HN. I'm not sure where to link from on the site however. Perhaps that's best as a separate issue?

**Comment by lwm** [comment]
> I also suggest an "FAQs" section in the wiki that could answer a bunch of the questions in HN. I'm not sure where to link from on the site however. Perhaps that's best as a separate issue?

Good idea! I've opened https://github.com/giving-a-fuck-about-climate-change/vision/issues/4 to track.
