### ISSUE TITLE
Font changes HN #16336140 comment

### ISSUE THREAD

**Issue by decentral1se** [giving-a-fuck-about-climate-change/carbon-inferno#171]
From https://news.ycombinator.com/item?id=16336140:

> Your font is hard to read because of the similarity between uppercase I and lowercase i & l. "Il" is identical and "il" only has one pixel difference.
> 
> You haven't used any j characters but they'd be similar to J.

**Comment by grady-lad** [comment]
Should we ping Purin about this one? @lwm @titojankowski

**Comment by lwm** [comment]
Summon the designer!

**Comment by titojankowski** [comment]
I was curious about this comment so I compared different fonts. Unless I'm misunderstanding, "il" has this issue in most fonts -- including Helvetica ililililil IlIlIlIlIl.
https://www.dropbox.com/s/c1h8zmcscizef7a/Screenshot%202018-04-22%2017.53.26.png?dl=0

That said, I agree the font on CarbonDoomsday does seem a bit hard to read. I think the cause is the "letter-spacing" property set at 1 px. Purin's original Keynote doc doesn't specify any specific letter-spacing. While 0 px doesn't look good either, 0.1 px looks good. See screenshots below. 

Thoughts on 0.1px letter spacing @grady-lad @lwm @stephanieinez?

1 px (current): https://www.dropbox.com/s/uj1ttc5qte7q2vw/Screenshot%202018-04-22%2018.01.39.png?dl=0
0 px (too squeezed IMO): https://www.dropbox.com/s/6lc79g5xg5ws7tu/Screenshot%202018-04-22%2018.02.38.png?dl=0
0.1 px (proposed: https://www.dropbox.com/s/g7tvkh686n4syq6/Screenshot%202018-04-22%2018.01.49.png?dl=0
